"""
This code is generated by Ridvan Salih KUZU
LAST EDITED:  20.06.2022
ABOUT SCRIPT:
It is used to set downstream Task Type for few shot learning
"""

from enum import Enum

class TaskType(Enum):
    DEFAULT = 0
    ARC_HEAD = 1
    MLP_HEAD = 2
    ARC_MLP_HEAD = 3
    HYPERVIEW = 4